// pages/species/species.js — 鱼种图鉴
const SPECIES_DATA = [
  {
    id: 1, name: '黑鲷', en: 'Black Seabream', icon: '🐟',
    category: '鲷科', habitat: '沿岸礁石、泥底沙滩',
    season: '全年，春秋最佳',
    size: '20-40cm，最大可达60cm',
    weight: '0.5-2kg，大型个体达4kg',
    bait: '沙蚕（首选）、螃蟹、贝肉、虾',
    rig: '天秤、游动铅、Hi-Lo',
    rodPower: 'medium（20-30号铅）',
    tips: '夜钓效果更佳；磷光诱饵在混水中表现好；涨潮前后1小时为黄金时段',
    color: '#2d6a8f',
  },
  {
    id: 2, name: '鲈鱼', en: 'Japanese Seabass', icon: '🐠',
    category: '鲈科', habitat: '河口、浅礁、砂石底质',
    season: '春秋最佳，冬季深水区',
    size: '30-60cm，最大达1m',
    weight: '1-5kg',
    bait: '小活鱼、沙蚕、虾、路亚',
    rig: '泳层铅、游动铅',
    rodPower: 'medium-heavy（25-35号铅）',
    tips: '喜欢追逐小鱼；清晨黄昏最活跃；涨潮时到浅水区觅食',
    color: '#3d7a5e',
  },
  {
    id: 3, name: '石斑鱼', en: 'Grouper', icon: '🐡',
    category: '鮨科', habitat: '礁石、岩缝、珊瑚礁',
    season: '夏季最旺',
    size: '30-70cm',
    weight: '1-10kg',
    bait: '小活鱼（首选）、鱿鱼条、沙蚕',
    rig: 'Bottom rig、游动铅',
    rodPower: 'heavy（30-40号铅）',
    tips: '穴居性，目标礁石下的阴暗处；一旦咬钩立即控制防止入洞',
    color: '#7a4a2d',
  },
  {
    id: 4, name: '鲻鱼', en: 'Mullet', icon: '🐟',
    category: '鲻科', habitat: '河口、港口、沙滩',
    season: '全年，秋冬最佳',
    size: '30-60cm',
    weight: '0.5-3kg',
    bait: '面团（最有效）、沙蚕、藻类',
    rig: 'Hi-Lo、浮标钓',
    rodPower: 'medium（20-25号铅）',
    tips: '群居性，发现一条往往有群；对气味敏感，打窝效果好',
    color: '#4a7a3d',
  },
  {
    id: 5, name: '鲭鱼', en: 'Mackerel', icon: '🐟',
    category: '鲭科', habitat: '开放海域、水体中层',
    season: '春秋洄游季',
    size: '25-45cm',
    weight: '0.3-1.5kg',
    bait: '虾皮、沙蚕、路亚、Sabiki',
    rig: 'Sabiki、竖钓',
    rodPower: 'medium（20-25号铅）',
    tips: '洄游鱼种，关注季节；海面有鸟群追逐处往往有鱼群',
    color: '#2d5a8f',
  },
  {
    id: 6, name: '带鱼', en: 'Cutlassfish', icon: '🐟',
    category: '带鱼科', habitat: '深水沙泥底质',
    season: '秋冬最旺',
    size: '60-120cm（体宽4-8cm）',
    weight: '0.5-3kg',
    bait: '小活鱼、鱿鱼条、闪光路亚',
    rig: 'Bottom rig、拖钓',
    rodPower: 'medium-heavy（25-35号铅）',
    tips: '夜钓效果极佳；对反光体有强烈攻击欲望；钓获后小心牙齿',
    color: '#8f7a2d',
  },
  {
    id: 7, name: '黄鱼', en: 'Yellow Croaker', icon: '🟡',
    category: '石首鱼科', habitat: '近海沙底、礁石区',
    season: '春夏洄游季',
    size: '20-45cm',
    weight: '0.3-2kg',
    bait: '虾、沙蚕、小鱿鱼',
    rig: 'Hi-Lo、游动铅',
    rodPower: 'medium（20-30号铅）',
    tips: '声音捕食，咬钩后有"咕咕"声；群居，发现鱼群可集中作钓',
    color: '#d4a017',
  },
  {
    id: 8, name: '金头鲷', en: 'Gilthead Seabream', icon: '🐟',
    category: '鲷科', habitat: '沙底、海草床',
    season: '秋冬最佳',
    size: '25-50cm',
    weight: '0.5-3kg',
    bait: '贝类、螃蟹、沙蚕',
    rig: 'Hi-Lo、天秤',
    rodPower: 'medium（20-27号铅）',
    tips: '咬合力强，喜欢吃贝类；礁石与沙底交界处是热点区',
    color: '#d4b017',
  },
  {
    id: 9, name: '笛鲷', en: 'Snapper', icon: '🔴',
    category: '笛鲷科', habitat: '礁石、珊瑚区',
    season: '全年，夏季最旺',
    size: '25-55cm',
    weight: '0.5-4kg',
    bait: '鱿鱼、虾、小活鱼',
    rig: 'Bottom rig、Hi-Lo',
    rodPower: 'medium-heavy（25-35号铅）',
    tips: '鲜艳的红色体色；群居性；礁石区底钓效果好',
    color: '#c0392b',
  },
  {
    id: 10, name: '海鳗', en: 'Sea Eel', icon: '🐍',
    category: '鳗科', habitat: '礁石洞穴、泥底深坑',
    season: '夏秋最旺',
    size: '60-150cm',
    weight: '1-8kg',
    bait: '沙蚕（最有效）、小活鱼、鱿鱼',
    rig: 'Bottom rig（单钩）',
    rodPower: 'heavy（30-40号铅）',
    tips: '夜钓专属；咬钩后旋转逃跑，需要足够刹车力；抄网必备',
    color: '#4a3d2d',
  },
  {
    id: 11, name: '鲹鱼', en: 'Amberjack/Trevally', icon: '🐟',
    category: '鲹科', habitat: '开放海域、礁石周边',
    season: '夏秋',
    size: '25-60cm',
    weight: '0.5-5kg',
    bait: '路亚（快速小型）、竖钓、沙蚕',
    rig: 'Jig、Sabiki',
    rodPower: 'medium-heavy（25-33号铅）',
    tips: '高速追饵鱼种；路亚收线速度要快；礁石外围水流处',
    color: '#2d6a4a',
  },
  {
    id: 12, name: '鲻鱼', en: 'Striped Mullet', icon: '🐟',
    category: '鲻科', habitat: '浅海沙滩、河口',
    season: '全年',
    size: '25-50cm',
    weight: '0.5-2kg',
    bait: '面团、虾、藻类',
    rig: '浮标、Hi-Lo',
    rodPower: 'medium（18-25号铅）',
    tips: '嘴小，用细线细钩效果更好',
    color: '#5a7a3d',
  },
  {
    id: 13, name: '比目鱼', en: 'Flounder', icon: '🐟',
    category: '鲽科', habitat: '沙底平坦区域',
    season: '秋冬最佳',
    size: '20-50cm',
    weight: '0.3-2kg',
    bait: '沙蚕、活虾、小活鱼',
    rig: '天秤（慢速移动）',
    rodPower: 'medium（20-27号铅）',
    tips: '贴底鱼种，缓慢移动天秤；咬钩后感觉重量增加而不猛烈',
    color: '#8f7a5a',
  },
  {
    id: 14, name: '河豚', en: 'Puffer Fish', icon: '⚠️',
    category: '鲀科', habitat: '近岸各种底质',
    season: '春秋',
    size: '15-40cm',
    weight: '0.2-1.5kg',
    bait: '沙蚕、虾、贝肉',
    rig: '任何底钓组',
    rodPower: 'medium（20-27号铅）',
    tips: '⚠️ 内脏有剧毒，禁止食用。如钓获，请戴手套处理后放流',
    color: '#e85555',
  },
  {
    id: 15, name: '鲷鱼（真鲷）', en: 'Red Sea Bream', icon: '🔴',
    category: '鲷科', habitat: '礁石区、沙底',
    season: '春秋最佳，全年可钓',
    size: '30-60cm',
    weight: '0.5-5kg',
    bait: '虾、沙蚕、螃蟹',
    rig: '天秤、游动铅、Hi-Lo',
    rodPower: 'medium（20-30号铅）',
    tips: '日本钓鱼文化中最重要的鱼种；涨落潮交替时最活跃',
    color: '#c0392b',
  },
];

Page({
  data: {
    allSpecies: SPECIES_DATA,
    filtered: SPECIES_DATA,
    keyword: '',
    selectedId: null,
    selectedItem: null,
  },

  onSearch(e) {
    const kw = e.detail.value.toLowerCase();
    this.setData({
      keyword: kw,
      filtered: kw
        ? SPECIES_DATA.filter(s => s.name.includes(kw) || s.en.toLowerCase().includes(kw))
        : SPECIES_DATA,
    });
  },

  onTap(e) {
    const id = e.currentTarget.dataset.id;
    const item = SPECIES_DATA.find(s => s.id === id);
    this.setData({ selectedId: id, selectedItem: item });
  },

  closeDetail() {
    this.setData({ selectedId: null, selectedItem: null });
  },

  goRecord() {
    wx.navigateTo({ url: '/pages/catch-log/catch-log' });
  },
});
